### PR TITLE
Update launch files to declare WebotsController node

### PR DESCRIPTION
**Pull request by ygoumaz**
_Internal review_

Update launch files of the tutorial to the new `WebotsController` node added in https://github.com/cyberbotics/webots_ros2/pull/746.

This should be merged to the official documentation only when Webots R2023b is released, as the feature in only on develop for now.

### CODE REVIEW

**Comment by ygoumaz** [comment]
I have added the minimal version of Webots and package to have to follow the instructions of the tutorial. I believe it is good for us and the user to know how far it has been udpated and version limitations.

**Review by omichel — APPROVED** [review]
Thank you.

**Comment by ygoumaz** [comment]
I forgot to do it on the second one...

**Comment by omichel** [comment]
I would also include upcoming versions in the new sentence.

**Review by omichel — APPROVED** [review]
Thank you.

**Pull request merged**
